modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "blockpops"
version = "${version}"
displayName = "BlockPops"
authors = "ThePlumTeam"
description = '''
BlockPops - A Minecraft mod featuring animated blocks and interactive gameplay mechanics.
'''
#logoFile = ""

[[dependencies.blockpops]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockpops]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockpops]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
